name: Test Secrets

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check if secrets exist
        run: |
          echo "Testing secrets..."
          if [ -z "${{ secrets.SSH_HOST }}" ]; then
            echo "❌ SSH_HOST is empty"
          else
            echo "✅ SSH_HOST is set"
          fi
          
          if [ -z "${{ secrets.SSH_USER }}" ]; then
            echo "❌ SSH_USER is empty"
          else
            echo "✅ SSH_USER is set"
          fi
          
          if [ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
            echo "❌ SSH_PRIVATE_KEY is empty"
          else
            echo "✅ SSH_PRIVATE_KEY is set"
          fi
